language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
# command to run tests
script:
  - pytest
  - pytest --cov="times" --cov-report html